### ISSUE TITLE
Add spaces around direct descendant selector

### ISSUE THREAD

**Issue by KolyaKorruptis** [mblander/formate#12]
![image](https://user-images.githubusercontent.com/4076947/107021596-a2e2c480-67a4-11eb-9798-cd3a1af7b983.png)

It would be nice if the direct descendant selector ">" was wrapped in spaces. 🙂

**Comment by ginesufa** [comment]
I fully agree with you, we need such a setup

**Comment by mblander** [comment]
There is a official bug in js-beautify, the base package I use. As soon as they resolve the issue I will update formate.

https://github.com/beautify-web/js-beautify/issues/676
