### ISSUE TITLE
could not format scss

### ISSUE THREAD

**Issue by Mordef** [mblander/formate#20]
VSCode September 2021 (version 1.61)
Extension: v1.2.0

All worked fine, but today i get this exeption:

![image](https://user-images.githubusercontent.com/22061464/137754136-b9e70813-e617-430d-bcbf-bf636766997c.png)

Allready have desintalled and install new.

**Comment by bogdan-patraucean** [comment]
I encountered the same issue.

**Comment by mblander** [comment]
Hi Mordef and bogdan-patraucean,

Thank you for reporting the issue! I just reverted the extension to a version that worked.
My apologies that this happened I hope that you continue to use Formate.

I will release the next version after a bit more testing and fixing the reported issue.

Mike Bovenlander

**Comment by Mordef** [comment]
Thank you Mike, it works 👍
