### ISSUE TITLE
Add `formate.verticalAlignPropertiesOnComments` option

### ISSUE THREAD

**Issue by almino** [mblander/formate#5]
WordPress doesn't handle well spaces before colons on the first comment block of its `style.css` file. This first comment block is used to provide [theme metadata](https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/#example).

When we format the file, the theme metadata is vertical aligned and the theme becomes kind of broken. So it shouldn't be vertical aligned.

Please add this option to the extension.

An alternative is to not vertical align properties when they're in a `/*!` comment block. Or in a header comment section / block.

**Comment by mblander** [comment]
Hi Almino, 

Thanks for reporting this issue. I've just released (v1.1.5) a fix to skip commments/comment sections from vertically formatting.

Hope it works, 

Mike
