### ISSUE TITLE
how do you cofigure

### ISSUE THREAD

**Issue by crispylemons** [mblander/formate#6]
formate.verticalAlignProperties

There is no documentaction online.

**Comment by mblander** [comment]
There is only a limited amount of options.
Did you check the default github landing page or the vscode marketplace page:

- https://github.com/mblander/formate#extension-settings
- https://marketplace.visualstudio.com/items?itemName=MikeBovenlander.formate&ssr=false#overview

**Comment by crispylemons** [comment]
you stupid
