### ISSUE TITLE
Proposal: Field for align colon

### ISSUE THREAD

**Issue by Piets0n** [mblander/formate#8]
Hey, thanks for this extension, i quite like it! 

But i think that the colon between the values is also aligning looks a bit odd.

its almost the same effect then, as you can do in the SCSS files in PHP/Web Storm with the align to value option

![Bildschirmfoto 2020-04-02 um 16 42 21](https://user-images.githubusercontent.com/44985277/78262588-11aa1e00-7501-11ea-8235-d97ecd897556.png)

So i cloned this project and created a new branch and want to pull request it, but i think i don't have permission. I didn't test anything, but i think you'll get the idea.

How are you handling this?

**Comment by mblander** [comment]
Hi Piets0n, 

You should be able to create an pull request. There are no permissions set for this. 

Thanks in advance!

Mike

**Comment by mblander** [comment]
I've added unit tests and merged you're changes to master. There in version 1.1.5. Thank you for contribution!
